#!/usr/bin/env perl
#Written by Manan Shah v1 
#contact: m.shah@ncl.res.in or manan.b.shah@gmail.com 
#Add comments here to list changelog
use strict;
use warnings;
print "
Path2Class

This Script is designed to convert output of KO2Path to a sublevel level profile using kegg.jp as reference.

Developed on and for Unix/Linux.
If you are behind a proxy before the program is executed you will need to set proxy address as:

export http_proxy://user:password\@proxyaddress:port/

Thank you for using this program
--Developed by Manan Shah
contact: m.shah\@ncl.res.in or manan.b.shah\@gmail.com

Free to be modified by fellow researchers. Would suggest adding a comment lines to describe the changes made.
";
																		#opening the Tax4Fun output
my $filepath;
my $keyword;
if ( exists($ARGV[0])){
	$filepath=$ARGV[0];
}else{
	print "Please Enter File Name:";
	chomp($filepath=<STDIN>);
	$filepath=$filepath;
}
print "\nFile Bieng Processed $filepath\n";
if ( exists($ARGV[1])){
	$keyword=$ARGV[1];
	print "sub-class keyword:$keyword";
}else{
	
	print "Sub-Class (Keyword)[Leave Blank If not required]:";
	chomp($keyword=<STDIN>);
}

open (my $fh, "<", $filepath);
chomp(my $headerline=<$fh>);
my @headers=split("\t",$headerline);
shift(@headers);														#identifying the sample IDs

my @arrayofhashes;														#declaring global variables
my @unique_slevels;
my $indetcount=0;
my %ClassCount;
my @keyword_array;
my %keyword_profile;

print "\n";
print "processing identifier no:\n";
foreach my $line (<$fh>){												#reading each line of Tax4Fun file
	if ($line=~/(ko\d+)\s(.+)/){											#identifying kegg orthology identifiers
		if($line!~/^Unknown/){
			print "\b\b\b\b\b";
			my @line_split= split("\t",$2);
			my $kidentifier=$1;
			my $prot=$line_split[0];
			my @slevels=find_slevels($kidentifier,$prot);
			$indetcount++;
			print "$indetcount";
			if (exists $keyword_profile{$kidentifier}){
				$keyword_profile{$kidentifier}=$line;
			}
			if (scalar(@slevels)!=0){
				calculate_slevel_profile($line,\@slevels);
			}
		}
	}
}

close($fh);																#close Tax4Fun file
$filepath=~s/_pathwaysprofile.tsv//g;
my $outfilename=$filepath."_sublevelprofile.tsv";
my $outfile2=$filepath."_classkeywordprofile.tsv";
print "\n\nOutput saved to $outfilename\n";


#Writing Sublevel Profile
open (my $output, ">",$outfilename);									#open OUTPUT file;
print $output "\"KEGG_Class(slevel Counts)\"\t";foreach(@headers){print $output "$_\t";};print $output "\n"; #printing the header line in output
@unique_slevels= sort @unique_slevels;
for(my $i=0;$i<scalar(@unique_slevels);$i++){							#printing the sublevel profile
	my $thisslevel=$unique_slevels[$i];
	my $class_count=$ClassCount{$thisslevel}/scalar(@headers);
	print $output "\"$thisslevel($class_count)\"\t";
	for(my $x=0;$x<scalar(@headers);$x++){
		print $output "$arrayofhashes[$x]{$thisslevel}\t";
	}
	print $output "\n";
}
close ($output);

#Writing Keyword Profile
if($keyword=~/\w/){
	open (my $output2, ">",$outfile2);									#open OUTPUT file number 2 for keywords;
	print $output2 "\"KEGG_slevel\"\t";foreach(@headers){print $output2 "$_\t";};print $output2 "\n"; #printing the header line in output
	print "the pathways from class with keyword $keyword are: \n";
	for (my $x=0; $x<scalar(@keyword_array);$x++){
		print "$keyword_array[$x]\n";
		print $output2 "$keyword_profile{$keyword_array[$x]}";
	}
	close($output2);
}

sub find_slevels{														#subroutine to fetch kegg slevels from KEGG
	my $kid=$_[0];
	my $prot=$_[1];
	my $ddir="/home/ncim/Softwares/ancillary/Kegg/";
	opendir my $dir, $ddir or die "Cannot open directory: $ddir $!";
	my @kegg_folder = readdir $dir;
	closedir $dir;
	my @try;
	my $keggfolderstring="@kegg_folder";
	if($keggfolderstring=~/\s$kid\s/){
		my $kegg_file=$ddir.$kid;
		@try=`cat $kegg_file`;
	}else{
		my $kegg_file=$ddir.$kid;
		my @try2=`curl -s http://rest.kegg.jp/get/$kid >$kegg_file`;
		@try=`cat $kegg_file`;
	}

	my $flag=0;
	my @out;
	my $ret;
	foreach my $kline(@try){
		if($kline=~/^\w/){$flag=0;}
		if($kline=~/^CLASS\s+(.*)/){
			my $koid=$1;
			push (@out,$koid);
			if($koid=~/$keyword/)
			{
				push(@keyword_array,"$kid");
				$keyword_profile{$kid}="";
			}
		}
		
	}
	#print scalar(@out);
	if (scalar(@out)<1){push (@out, "unknown class $prot--$kid")}
	return @out;
}



sub calculate_slevel_profile{											#subroutine to process the profile into one table
	my $line=$_[0];
	my $rslevels=$_[1];
	my @slevels=@$rslevels;
	my @raw_values=split("\t",$line);
	shift(@raw_values);
	for(my $i=0;$i<scalar(@headers);$i++){
		my $value=$raw_values[$i];
		my $devidevalues=$value/scalar(@slevels);
		foreach my $slevel(@slevels){
			#my $uniqueslevelstring="@unique_slevels";
			#if ( $uniqueslevelstring=~/\s$slevel\s/ ) {
			if ($slevel~~@unique_slevels){
				my $tmp=$ClassCount{$slevel};
				$tmp++;
				$ClassCount{$slevel}=$tmp;
				} else{
					push(@unique_slevels,$slevel);
					$ClassCount{$slevel}=1;
				}
			if (exists $arrayofhashes[$i]{$slevel}){
				my $tmp=$arrayofhashes[$i]{$slevel};
				$tmp=$tmp+$devidevalues;
				$arrayofhashes[$i]{$slevel}=$tmp;
				}else{
					$arrayofhashes[$i]{$slevel}=$devidevalues;
					}
			
		}

	}

}
